"""Prequestions

Revision ID: 9036354aea7c
Revises: 
Create Date: 2022-09-02 23:03:37.871662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9036354aea7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prequestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('education', sa.String(length=15), nullable=True),
    sa.Column('major', sa.String(length=15), nullable=True),
    sa.Column('timeSpent', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prequestions_age'), 'prequestions', ['age'], unique=False)
    op.create_index(op.f('ix_prequestions_education'), 'prequestions', ['education'], unique=False)
    op.create_index(op.f('ix_prequestions_gender'), 'prequestions', ['gender'], unique=False)
    op.create_index(op.f('ix_prequestions_major'), 'prequestions', ['major'], unique=False)
    op.create_index(op.f('ix_prequestions_timeSpent'), 'prequestions', ['timeSpent'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prequestions_timeSpent'), table_name='prequestions')
    op.drop_index(op.f('ix_prequestions_major'), table_name='prequestions')
    op.drop_index(op.f('ix_prequestions_gender'), table_name='prequestions')
    op.drop_index(op.f('ix_prequestions_education'), table_name='prequestions')
    op.drop_index(op.f('ix_prequestions_age'), table_name='prequestions')
    op.drop_table('prequestions')
    # ### end Alembic commands ###
